export { User, UserRole } from './user.entity';
export { Student, StudentStatus } from './student.entity';
export { Doctor, DoctorTitle } from './doctor.entity';
export { Ta } from './ta.entity';
export { Advisor } from './advisor.entity';
export { Department, Faculty } from './department.entity';
export { Program, Degree } from './program.entity';
export { Course } from './course.entity';
export { Semester, SemesterType } from './semester.entity';
export { AcademicYear } from './academic-year.entity';
export { CourseRegistration, RegistrationStatus } from './course-registration.entity';
export { Attendance, AttendanceStatus, AttendanceMethod } from './attendance.entity';
export { Lecture, LectureType } from './lecture.entity';
export { Grade, GradeComponent } from './grade.entity';
export { Exam, ExamType } from './exam.entity';
export { ExamSchedule } from './exam-schedule.entity';
export { Classroom, ClassroomType } from './classroom.entity';
export { Notification, NotificationType } from './notification.entity';
export { AiConversation, ConversationRole, ConversationLanguage } from './ai-conversation.entity';
export { Schedule, ScheduleType, ScheduleStatus } from './schedule.entity';
export { AuditLog } from './audit-log.entity';
export { CourseMaterial, MaterialType } from './course-material.entity';
export { Announcement, AnnouncementPriority } from './announcement.entity';
export { Warning, WarningType } from './warning.entity';
export { GpaHistory } from './gpa-history.entity';
export { SystemSetting } from './system-setting.entity';
