apiVersion: v1
kind: Secret
metadata:
  name: fee-menouf-secrets
  namespace: fee-menouf
  labels:
    app.kubernetes.io/part-of: fee-menouf-platform
type: Opaque
stringData:
  DB_PASS: "CHANGE_ME"
  REDIS_PASSWORD: "CHANGE_ME"
  JWT_ACCESS_SECRET: "CHANGE_ME"
  JWT_REFRESH_SECRET: "CHANGE_ME"
  ENCRYPTION_KEY: "CHANGE_ME"
  MINIO_ROOT_PASSWORD: "CHANGE_ME"
  OPENAI_API_KEY: ""
  SESSION_SECRET: "CHANGE_ME"
  CSRF_SECRET: "CHANGE_ME"
  MINIO_ROOT_USER: "minioadmin"
  SMTP_PASS: "CHANGE_ME"
